spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: userservice                  #RouteIdentifier
          uri: lb://UserService            #Respective Microservices url which needs to be mapped
          predicates:
            - Path=/user/**                #Request Context Path Mapping
          filters:
            - name: CircuitBreaker
              args:
                name: userservice
                fallbackuri: forward:/userFallBack
        - id: bookservice
          uri: lb://BookService
          predicates:
            - Path=/book/**
          filters:
            - name: CircuitBreaker
              args:
                name: bookservice
                fallbackuri: forward:/bookFallBack
        - id: cartservice
          uri: lb://CartService
          predicates:
            - Path=/cart/**
          filters:
            - name: CircuitBreaker
              args:
                name: cartservice
                fallbackuri: forward:/cartFallBack
        - id: orderservice
          uri: lb://OrderService
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderservice
                fallbackuri: forward:/orderFallBack
        - id: paymentservice
          uri: lb://PaymentService
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentservice
                fallbackuri: forward:/paymentFallback


server:
  port: 8989

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100
